[package]
name = "genericity"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
nom = "8.0.0"
olympus = { path = "../../olympus" }

[[bin]]
name = "watershed_image2d"
path = "src/watershed_image2d.rs"

[[bin]]
name = "watershed_node_graph"
path = "src/watershed_node_graph.rs"

[[bin]]
name = "off_parser"
path = "src/off_parser.rs"
